"""empty message

Revision ID: e309f88fa1cf
Revises: 5fd088968200
Create Date: 2023-07-04 17:10:46.090073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e309f88fa1cf'
down_revision = '5fd088968200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(), nullable=False))
    op.create_unique_constraint("email", "users", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("email", "users", type_="unique")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
